### ISSUE TITLE
last mile latency measurement parsing error 

### ISSUE THREAD

**Issue by ggmartins** [chicago-cdac/nm-exp-active-netrics#129]
netrics -b

```
 --- NETWORK MEASUREMENTS ---

 --- google ping latency (MANDATORY) ---
Packet Loss: 0.0%
Average RTT: 35.636 (ms)
Minimum RTT: 43.121 (ms)
Maximum RTT: 58.545 (ms)
RTT Std Dev: 6.759 (ms)
Traceback (most recent call last):
  File "./src/netrics.py", line 360, in <module>
    output['last_mile_rtt'] = test.last_mile_latency('last_mile_rtt', args.last_mile_rtt)
  File "/usr/local/src/nm-exp-active-netrics/src/netrics/netson.py", line 262, in last_mile_latency
    return test_last_mile_latency(key, self, self.nma.conf, self.results, self.quiet)
  File "/usr/local/src/nm-exp-active-netrics/src/netrics/builtin/netrics_test_last_mile_latency.py", line 35, in test_last_mile_latency
    parse_trace_output(out,output,site,results,key,labels)
  File "/usr/local/src/nm-exp-active-netrics/src/netrics/builtin/netrics_test_last_mile_latency.py", line 45, in parse_trace_output
    ip_addr = re.findall(ipv4_extract_pattern, line)[0]
IndexError: list index out of range
```

**Comment by ggmartins** [comment]
this is happening because traceroute to 1.1.1.1 does not show any non-local ipv4 address:
```
traceroute to 1.1.1.1 (1.1.1.1), 30 hops max, 60 byte packets
 1  192.168.12.1 (192.168.12.1)  0.638 ms  0.440 ms  0.351 ms
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```
