### ISSUE TITLE
ping_latency to multiple targets breaking because of a single failure

### ISSUE THREAD

**Issue by ggmartins** [chicago-cdac/nm-exp-active-netrics#69]
FYI:
```
--- New_Delhi ping latency (MANDATORY) ---
Packet Loss: 0.0%
Average RTT: 252.867 (ms)
Minimum RTT: 253.8 (ms)
Maximum RTT: 257.69 (ms)
RTT Std Dev: 1.414 (ms)

--- Manila ping latency (MANDATORY) ---
Packet Loss: 9.09091%
Average RTT: 261.049 (ms)
Minimum RTT: 261.815 (ms)
Maximum RTT: 266.09 (ms)
RTT Std Dev: 1.437 (ms)

--- Sydney ping latency (MANDATORY) ---
Packet Loss: 0.0%
Average RTT: 216.515 (ms)
Minimum RTT: 217.208 (ms)
Maximum RTT: 218.331 (ms)
RTT Std Dev: 0.651 (ms)

--- Sao_Paulo ping latency (MANDATORY) ---
Packet Loss: 0.0%
Average RTT: 163.812 (ms)
Minimum RTT: 164.742 (ms)
Maximum RTT: 168.677 (ms)
RTT Std Dev: 1.364 (ms)
Traceback (most recent call last):
File "./src/netrics.py", line 290, in <module>
output['ping_latency'] = test.ping_latency('ping_latency', args.ping)
File "/usr/local/src/nm-exp-active-netrics/src/netrics/netson.py", line 310, in ping_latency
ping_rtt_ms = re.findall(
IndexError: list index out of range
```
and please K, do not code and commit without *serious* testing,  🙏 thanks, G.

**Comment by kyle-macmillan** [comment]
I will add error catches. My guess is there was no response from a destination.
