### ISSUE TITLE
Log Ookla JSON errors

### ISSUE THREAD

**Issue by marcwitasee** [chicago-cdac/nm-exp-active-netrics#80]
Some devices are experiencing a runtime error when loading the JSON response from Ookla speedtest:

```
Traceback (most recent call last):
File "./src/netrics.py", line 343, in <module>
output['ookla'] = test.speed_ookla('ookla', args.ookla)
File "/usr/local/src/nm-exp-active-netrics/src/netrics/netson.py", line 185, in speed_ookla
res_json = json.loads(output)
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

These errors are currently not logged. We should log them to see how frequently this type of error is occuring.

**Comment by marcwitasee** [comment]
Errors when loading the JSON output from an Ookla test have been logged with this commit: https://github.com/chicago-cdac/nm-exp-active-netrics/commit/1c4a5a33064755e5bd5fcdc4decc946635d35627, which has been merged and deployed on production. However, the error with Ookla is still occurring. We need to look into why the test is failing for certain devices.

Devices where this error is occurring include: `nm-mngd-20210915-8dd84998, nm-mngd-20210915-f4b4a69b, nm-mngd-20210927-3f24e5b4, nm-mngd-20210927-d8cfa28a`

**Comment by marcwitasee** [comment]
Fix deployed to Tigerteam devices.

**Comment by marcwitasee** [comment]
Fix deployed to wilson.

Changes:

- Wrap attempt to open json output after detecting an error  in initial output in try-catch statement
- Return the output from a failed attempt to run Ookla test so that the output is caught in the zip file produced by a Netrics run
