### ISSUE TITLE
error last_mile_latency

### ISSUE THREAD

**Issue by ggmartins** [chicago-cdac/nm-exp-active-netrics#85]
This error is crashing netrics preventing all other tests to run.
```
--- NETWORK MEASUREMENTS ---
Traceback (most recent call last):
File "./src/netrics.py", line 334, in <module>
output['last_mile_rtt'] = test.last_mile_latency('last_mile_rtt', args.last_mile_rtt)
File "/usr/local/src/nm-exp-active-netrics/src/netrics/netson.py", line 508, in last_mile_latency
res.sort()
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by tarunmangla** [comment]
I believe this should work. 

We may eventually also want to fix the parsing logic causing this issue. @ggmartins  do you know which device is facing this error? We can look at the raw logs to figure out what is causing it.

**Comment by ggmartins** [comment]
3db3
